### ISSUE TITLE
MFA doesn't show in user prefs if "No other factor" enabled

### ISSUE THREAD

**Issue by 90084** [catalyst/moodle-tool_mfa#378] opened 2023-04-27 06:28 UTC
MFA preferences doesn't show up in user preferences with "Authentication app" and "No other factors" enabled. This means user can't set up MFA via Preferences (although they can access page directly via admin/tool/mfa/user_preferences.php). I want to allow MFA as an option, _permanently_ (so "Grace period" doesn't suit). Preferences used to show in version 2020021401, but they're not showing on latest version 2023031600. I noticed some changes in manager.php:possible_factor_setup() back in 2020-03-20, so I'm surprised this hasn't been spotted, and lean towards assuming I'm missing something. Is it a bug? Docs note "This allows for an optional MFA rollout, where only users who wish to use MFA are affected by the MFA rollout." But this factor seems to block setting up MFA.
Thank you for a great plugin!

**Comment by danmarsden** [comment] 2023-04-27 06:42
This sounds like a duplicate of #330 pull requests are always welcome!

**Comment by 90084** [comment] 2023-04-27 22:52
Confirmed, thank you and my apologies, I did search but missed it. I will follow that ticket.

**Closed** 2023-04-27 22:53 UTC
