### ISSUE TITLE
Cannot open SCORM package on mobile

### ISSUE THREAD

**Issue by jefferson117** [catalyst/moodle-tool_mfa#298] opened 2021-05-25 12:45 UTC
When we activate mfa and an associated factor, we can no longer open scorm packages for a course from the mobile app (which is set for mobile authentication). If we enable any factor at all it breaks the mobile app.

Error when opening or downloading a course is "unzip failed". Cannot find anything logged on server to indicate a problem.

**Comment by brendanheywood** [comment] 2021-06-05 12:27
Is this broken completely, or broken just when you attempt to deep link into a scorm when you are not logged in and it fails to go through the login > mfa > scorm ?

**Comment by brendanheywood** [comment] 2022-07-28 17:20
I think the root cause here is that files downloaded this way don't have a session because NO_MOODLE_COOKIES is set

https://github.com/moodle/moodle/blob/master/webservice/pluginfile.php#L34

I think it is failing here:
https://github.com/catalyst/moodle-tool_mfa/blob/master/classes/manager.php#L497-L502

We should allow AJAX_SCRIPT with NO_MOODLE_COOKIES to be NO_REDIRECT rather than an exception

**Comment by Peterburnett** [comment] 2023-06-01 23:25
This one should be fixed now, NO_MOODLE_COOKIES is properly handled now. Closing

**Closed by Peterburnett** 2023-06-01 23:25 UTC
Labels: bug
